version: '3.8'
services:
  app: 
    image: nginx:1.23.2-alpine
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - './run.sh:/code/run.sh'
    working_dir: /code
    ports:
      - "80:80"
      - "443:443"
    command: ./run.sh

