site_name: My Docs
nav:
  - Home: index.md
  - subpage: subpage.md
  - 'navigation2':
    - 'Home': index.md
    - Subpage: subpage.md
  - 'navigation3':
    - 'Home': index.md
    - Subpage: subpage.md
theme: readthedocs